name: setup-zig
author: weskoerber
description: Sets up a Zig environment
inputs:
  zig_version:
    description: Zig version to use
    required: false
    default: 'master'
runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
      with:
        repository: weskoerber/zvm
        ref: main
        submodules: true
    - name: set zig version env variable
      run: echo "INPUT_ZIG_VERSION=${{ inputs.zig_version }}" >> "$GITHUB_ENV"
    - name: install zig ${INPUT_ZIG_VERSION}
      run: ./zvm --verbose install --use ${{ env.INPUT_ZIG_VERSION }}
      shell: sh
